name: Update Hugo dependencies

on:
  schedule:
    - cron: '0 3 * * *' # run daily at 03:00 AM
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-mod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'  # Replace with appropriate Node.js version
        cache: 'npm'

    - name: Install npm dependencies
      run: npm ci

    - name: Update Hugo module dependencies
      id: mod-updates
      run: |
        MOD_OUTPUT=$(npm run mod:update 2>&1)
        echo "$MOD_OUTPUT"
        MOD_UPDATES=$(echo "$MOD_OUTPUT" | grep '^go: upgraded' | sed 's/go: / - /' | sort -u)
        echo "$MOD_UPDATES" > MOD_UPDATES.txt

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.WORKFLOW_SECRET }}
        commit-message: 'fix: update Hugo module dependencies'
        committer: GitHub <noreply@github.com>
        branch: hugo-mod-dependencies
        delete-branch: true
        title: 'Update Hugo module dependencies'
        body: |
          This PR is auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request).
          
          Changes to go.mod:
          
          $(cat MOD_UPDATES.txt)

        labels: dependencies
        add-paths: |
          go.mod
          go.sum
